version: 2

gitea_urls:
  api: https://forgejo.home.arpa/api/v1
  download: https://forgejo.home.arpa
  skip_tls_verify: false

builds:
  - binary: lidarr-utils
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -w -s -X github.com/benscobie/lidarr-utils/cmd.version={{.Version}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
      - config.example.yaml

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
    - title: Bug fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
    - title: Others
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

dockers_v2:
  - images:
      - "forgejo.home.arpa/ben/lidarr-utils"
      - "benscobie/lidarr-utils"
    tags:
      - "{{ .Version }}"
      - "latest"
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - config.example.yaml
    platforms:
      - linux/amd64
      - linux/arm64
