FROM alpine:latest@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app

RUN addgroup -g 1001 -S appgroup && \
    adduser -u 1001 -S appuser -G appgroup

ARG TARGETPLATFORM
COPY ${TARGETPLATFORM}/lidarr-utils .
COPY config.example.yaml ./config.example.yaml

RUN mkdir -p /app/config && \
    chown -R appuser:appgroup /app

USER appuser

ENTRYPOINT ["./lidarr-utils"]
CMD ["--help"]
