FROM alpine:latest@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app

RUN addgroup -g 1001 -S appgroup && \
    adduser -u 1001 -S appuser -G appgroup

ARG TARGETPLATFORM
COPY ${TARGETPLATFORM}/lidarr-utils .
COPY config.example.yaml ./config.example.yaml

RUN mkdir -p /app/config && \
    chown -R appuser:appgroup /app

USER appuser

ENTRYPOINT ["./lidarr-utils"]
CMD ["--help"]
